# Generated by Django 4.2.1 on 2023-07-22 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.IntegerField(max_length=30)),
                ('Password', models.IntegerField(max_length=16)),
                ('Conpass', models.IntegerField(max_length=16)),
            ],
        ),
    ]
