# Generated by Django 4.2.1 on 2023-07-22 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='Conpass',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='register',
            name='Name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='register',
            name='Password',
            field=models.CharField(max_length=16),
        ),
    ]
